n1 = input('Digite algo: ')
print('O tipo primitivo desse valor é? ', type(n1))
print('Só contem espaços? ' , n1.isspace())
print('É um número? ' , n1.isnumeric())
print('É Alfabético? ' , n1.isalpha())
print('É Alfanúmerico? ' , n1.isalnum())
print('É maiúsculas? ' , n1.isupper())
print('É minúsculas? ' , n1.islower())
print('É captalizada? ' , n1.istitle())